"""
This script monitors a directory for the latest raw CBOR data file generated by the 8 Sleep Pod
and processes its CBOR-encoded biometric data in real-time.

Key functionalities:
- Watches the `/persistent` directory for new `.RAW` or `.cbor` files using `watchdog`.
- Tracks only the most recently modified raw data file, avoiding stale data.
- Reads CBOR-encoded lines from the active file and extracts biometric records.
- Filters and processes `piezo-dual` sensor data, ensuring only recent entries are used.
- Loads parsed piezoelectric sensor data into `load_piezo_row` and queues it for processing.
- Uses `StreamProcessor` to analyze incoming biometric records.
- Runs the monitoring and processing loop in a separate thread for efficiency.
- Handles graceful shutdown via KeyboardInterrupt.

Usage:
This is set up to run as a systemctl service, but you can manually run it with:
/home/dac/venv/bin/python /home/dac/free-sleep/biometrics/stream/stream.py
"""

import sys
import platform
import cbor2
import asyncio
import inspect
from datetime import datetime, timedelta
from collections import deque

if platform.system().lower() == 'linux':
    sys.path.append('/home/dac/free-sleep/biometrics/')
    sys.path.append('/home/dac/free-sleep/biometrics/stream/')

import time
import os
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler
import queue
import threading

from get_logger import get_logger
# Give time for the express.js server to boot
print('Sleeping for 30 seconds before starting stream service...')
time.sleep(30)
logger = get_logger('free-sleep-stream')

from stream_processor import StreamProcessor
from load_raw_files import load_piezo_row
from service_health import update_health

# Global queue for processing decoded biometric data
piezo_record_queue = queue.Queue()

STREAM_HEALTH_INTERVAL_SECONDS = 60
PARTIAL_CBOR_STALE_SECONDS = 30
PARTIAL_CBOR_LOG_INTERVAL_SECONDS = 60
RECENT_RECORD_WINDOW = timedelta(minutes=2)
STREAM_FILE_SUFFIXES = ('.RAW',)
NATS_URL = 'nats://127.0.0.1:4222'
NATS_STREAM = 'raw'
NATS_DURABLE = 'free_sleep_stream_live'
PROCESSED_SEQUENCE_LIMIT = 5000
processed_sequences = set()
processed_sequence_order = deque(maxlen=PROCESSED_SEQUENCE_LIMIT)


def _is_partial_cbor_error(error: Exception) -> bool:
    return 'premature end of stream' in str(error).lower()


def _safe_getmtime(path: str) -> float:
    try:
        if os.path.exists(path):
            return os.path.getmtime(path)
    except FileNotFoundError:
        logger.warning(f'File path not found, ignoring... {path}')
        pass
    return 0  # Default for missing files


def _is_stream_file_name(file_name: str) -> bool:
    return file_name != 'SEQNO.RAW' and file_name.endswith(STREAM_FILE_SUFFIXES)


def _mark_sequence_processed(sequence):
    if sequence is None:
        return
    if len(processed_sequence_order) == processed_sequence_order.maxlen:
        oldest = processed_sequence_order.popleft()
        processed_sequences.discard(oldest)
    processed_sequence_order.append(sequence)
    processed_sequences.add(sequence)


def _decode_raw_row(row):
    if not isinstance(row, dict):
        return None

    if row.get('data'):
        return cbor2.loads(row['data'])

    return row


def _queue_decoded_piezo_record(decoded_data) -> bool:
    if not isinstance(decoded_data, dict):
        logger.warning(f'Skipping unexpected nested CBOR value: {type(decoded_data)}')
        return False
    if decoded_data.get('type') != 'piezo-dual':
        return False
    if 'ts' not in decoded_data:
        logger.warning(f'Skipping piezo-dual record without timestamp: {decoded_data.keys()}')
        return False

    record_time = datetime.fromtimestamp(decoded_data['ts'])
    if datetime.now() - record_time > RECENT_RECORD_WINDOW:
        return False

    sequence = decoded_data.get('seq')
    if sequence in processed_sequences:
        return False

    load_piezo_row(decoded_data, 'right')
    piezo_record_queue.put(decoded_data)
    _mark_sequence_processed(sequence)
    return True


class LatestRawFileHandler(FileSystemEventHandler):
    """Monitors only the latest RAW file and processes CBOR-encoded lines separately."""

    def __init__(self, directory):
        self.directory = directory
        self.latest_file = None
        self.latest_file_obj = None
        self.last_pos = 0  # Track last read position
        self.partial_decode_pos = None
        self.partial_decode_size = None
        self.partial_decode_started_at = None
        self.partial_decode_logged_at = 0
        self.track_latest_file()

    def reset_partial_decode(self):
        self.partial_decode_pos = None
        self.partial_decode_size = None
        self.partial_decode_started_at = None
        self.partial_decode_logged_at = 0

    def handle_partial_decode(self, start_pos: int, error: Exception):
        current_size = os.fstat(self.latest_file_obj.fileno()).st_size
        now = time.monotonic()
        state_changed = (
            self.partial_decode_pos != start_pos
            or self.partial_decode_size != current_size
        )
        if state_changed:
            self.partial_decode_pos = start_pos
            self.partial_decode_size = current_size
            self.partial_decode_started_at = now
            self.partial_decode_logged_at = 0

        if now - self.partial_decode_started_at >= PARTIAL_CBOR_STALE_SECONDS:
            logger.warning(
                f'Skipping stale partial CBOR record in {self.latest_file} at byte '
                f'{start_pos}; file remained at {current_size} bytes for '
                f'{PARTIAL_CBOR_STALE_SECONDS} seconds. Last error: {error}'
            )
            self.last_pos = current_size
            self.latest_file_obj.seek(self.last_pos)
            self.reset_partial_decode()
            return

        if now - self.partial_decode_logged_at >= PARTIAL_CBOR_LOG_INTERVAL_SECONDS:
            logger.debug(
                f'Waiting for complete CBOR record in {self.latest_file} at byte '
                f'{start_pos}; current file size is {current_size}. Last error: {error}'
            )
            self.partial_decode_logged_at = now

    def track_latest_file(self):
        """Finds the most recent raw data file in the directory and starts tracking it."""
        stream_files = [f for f in os.listdir(self.directory) if _is_stream_file_name(f)]
        if not stream_files:
            return

        # Get the latest file by modification time
        stream_files.sort(
            key=lambda f: _safe_getmtime(os.path.join(self.directory, f)),
            reverse=True
        )

        latest_file = os.path.join(self.directory, stream_files[0])

        if latest_file != self.latest_file:
            # If a new file is found, stop tracking the old one
            self.latest_file = latest_file
            logger.debug(f"Now tracking: {self.latest_file}")

            # Close old file handle if open
            if self.latest_file_obj:
                self.latest_file_obj.close()

            # Open the new file for reading in binary mode
            self.latest_file_obj = open(self.latest_file, "rb")
            self.last_pos = 0  # Reset position for new file
            self.reset_partial_decode()

    def on_created(self, event):
        """Triggered when a new raw data file is created."""
        if event.is_directory or not _is_stream_file_name(os.path.basename(event.src_path)):
            return
        self.track_latest_file()

    def follow_latest_file(self):
        """Reads and decodes new CBOR-encoded lines from the latest file."""
        if not self.latest_file_obj:
            return

        # Move to the last known position before reading
        self.latest_file_obj.seek(self.last_pos)

        while True:
            start_pos = self.last_pos
            try:
                # Decode CBOR object from a **single line**
                row = cbor2.load(self.latest_file_obj)  # Load the next CBOR object
                self.last_pos = self.latest_file_obj.tell()
                self.reset_partial_decode()
                try:
                    decoded_data = _decode_raw_row(row)
                except Exception as error:
                    logger.warning(f'Error decoding nested CBOR data, skipping record: {error}')
                    continue
                _queue_decoded_piezo_record(decoded_data)

            except EOFError:
                # No more CBOR objects to read
                break
            except Exception as e:
                if _is_partial_cbor_error(e):
                    current_size = os.fstat(self.latest_file_obj.fileno()).st_size
                    if start_pos >= current_size:
                        self.reset_partial_decode()
                        break
                    self.handle_partial_decode(start_pos, e)
                    break
                logger.error(f"Error decoding CBOR, skipping malformed record: {e}")
                self.last_pos = self.latest_file_obj.tell()
                break


def process_biometrics():
    piezo_record = piezo_record_queue.get()
    stream_processor = StreamProcessor(piezo_record, debug=False)
    ix = 0
    while True:
        ix += 1
        if ix == 60:
            update_health('stream', 'healthy')
            ix = 0
        try:
            piezo_record = piezo_record_queue.get(timeout=5)

            if piezo_record is None:
                # Stop if None is received
                break

            stream_processor.process_piezo_record(piezo_record)
            piezo_record_queue.task_done()
        except queue.Empty:
            # Just continue if the queue is empty, do not exit the loop
            logger.info("No new data, retrying...")
        except Exception as error:
            logger.error(error)
            update_health('stream', 'failed', repr(error))


def watch_directory(directory="/persistent"):
    """Monitors the directory for new RAW files and processes only the latest one."""
    logger.info('Stream processor starting...')
    update_health('stream', 'started', '')
    handler = LatestRawFileHandler(directory)
    observer = Observer()
    observer.schedule(handler, directory, recursive=False)
    observer.start()
    last_health_update = time.monotonic()

    # Start biometric processing in a separate thread
    processing_thread = threading.Thread(target=process_biometrics, daemon=True)
    processing_thread.start()

    logger.debug('Stream processor set up successfully, running...')
    try:
        while True:
            time.sleep(1)
            if time.monotonic() - last_health_update >= STREAM_HEALTH_INTERVAL_SECONDS:
                update_health('stream', 'healthy', '')
                last_health_update = time.monotonic()
            handler.track_latest_file()  # Check if a newer file exists
            handler.follow_latest_file()  # Read new CBOR entries line-by-line
    except KeyboardInterrupt:
        observer.stop()
        piezo_record_queue.put(None)  # Send stop signal to processing thread
        processing_thread.join()
    except Exception as error:
        logger.error(error)
        update_health('stream', 'failed', repr(error))
        raise error

    observer.join()


async def _ack_message(message):
    ack_result = message.ack()
    if inspect.isawaitable(ack_result):
        await ack_result


async def watch_nats_stream():
    try:
        import nats
        from nats.errors import TimeoutError as NatsTimeoutError
        from nats.js.api import AckPolicy, ConsumerConfig, DeliverPolicy
    except ImportError as error:
        raise RuntimeError('nats-py is not installed') from error

    logger.info('NATS stream processor starting...')
    update_health('stream', 'started', '')

    processing_thread = threading.Thread(target=process_biometrics, daemon=True)
    processing_thread.start()

    nc = None
    try:
        nc = await nats.connect(NATS_URL, connect_timeout=5)
        js = nc.jetstream()
        stream_info = await js.stream_info(NATS_STREAM)
        subjects = getattr(stream_info.config, 'subjects', None) or [NATS_STREAM]
        subject = subjects[0]
        logger.info(f'Consuming NATS JetStream stream={NATS_STREAM} subject={subject}')

        consumer_config = ConsumerConfig(
            durable_name=NATS_DURABLE,
            deliver_policy=DeliverPolicy.NEW,
            ack_policy=AckPolicy.EXPLICIT,
        )
        subscription = await js.pull_subscribe(
            subject,
            durable=NATS_DURABLE,
            stream=NATS_STREAM,
            config=consumer_config,
        )
        last_health_update = time.monotonic()
        queued_count = 0

        while True:
            if time.monotonic() - last_health_update >= STREAM_HEALTH_INTERVAL_SECONDS:
                update_health('stream', 'healthy', '')
                last_health_update = time.monotonic()
                logger.debug(f'NATS stream heartbeat; queued piezo records={queued_count}')

            try:
                messages = await subscription.fetch(25, timeout=5)
            except NatsTimeoutError:
                continue

            for message in messages:
                try:
                    row = cbor2.loads(message.data)
                    decoded_data = _decode_raw_row(row)
                    if _queue_decoded_piezo_record(decoded_data):
                        queued_count += 1
                    await _ack_message(message)
                except Exception as error:
                    logger.warning(f'Error decoding NATS raw message, acknowledging and skipping: {error}')
                    await _ack_message(message)
    finally:
        if nc is not None:
            await nc.close()
        piezo_record_queue.put(None)
        processing_thread.join(timeout=5)


def watch_stream():
    try:
        asyncio.run(watch_nats_stream())
    except Exception as error:
        logger.warning(f'NATS stream unavailable, falling back to RAW file watcher: {error}')
        watch_directory("/persistent")


# Start watching and processing live biometrics data.
watch_stream()
